### ISSUE TITLE
Return an empty value

### ISSUE THREAD

**Issue by SSebigo** [skreborn/rustic#1]
Hi, I was wondering there was a built-in type representing an empty value.
For example, in Dartz they have the ```Unit``` type.

I'm quite a fan of Rust and I find this approach of handling errors more elegant than Dartz one but on the other hand, having a built-in type for empty values is quite nice too instead of returning ```null```.

tl,dr: Is there a built-in type for empty values?

**Comment by skreborn** [comment]
**Heads up!** As of May 10, 2023, the `Unit` type, along with the entire `tuple` library is going away in favor of Dart 3's built-in records.

---

_Original answer:_

Sure there is! It is indeed called [`Unit`](https://pub.dev/documentation/rustic/latest/tuple/Unit-class.html), and it's defined - like in Rust - as an empty [`Tuple`](https://pub.dev/documentation/rustic/latest/tuple/Tuple-class.html).
